### ISSUE TITLE
UnicodeEncodeError: `ascii` codec can't encode characters

### ISSUE THREAD

**Issue by hershelm** [pyscaffold/pyscaffoldext-dsproject#1]
When I run `putup --dsproject test_ds_proj` on my local MacBook Pro (OS: Mojave), I am able to create the project structure, but I get the following error. Have you encountered this?

=== 

$ putup --dsproject test_ds_proj
Traceback (most recent call last):
  File "/Users/hershel.mehta/miniconda3/envs/advent2017/bin/putup", line 10, in <module>
    sys.exit(run())
  File "/Users/hershel.mehta/miniconda3/envs/advent2017/lib/python3.6/site-packages/pyscaffold/shell.py", line 71, in func_wrapper
    func(*args, **kwargs)
  File "/Users/hershel.mehta/miniconda3/envs/advent2017/lib/python3.6/site-packages/pyscaffold/utils.py", line 143, in func_wrapper
    func(*args, **kwargs)
  File "/Users/hershel.mehta/miniconda3/envs/advent2017/lib/python3.6/site-packages/pyscaffold/cli.py", line 232, in run
    main(sys.argv[1:])
  File "/Users/hershel.mehta/miniconda3/envs/advent2017/lib/python3.6/site-packages/pyscaffold/cli.py", line 225, in main
    opts['command'](opts)
  File "/Users/hershel.mehta/miniconda3/envs/advent2017/lib/python3.6/site-packages/pyscaffold/cli.py", line 194, in run_scaffold
    api.create_project(opts)
  File "/Users/hershel.mehta/miniconda3/envs/advent2017/lib/python3.6/site-packages/pyscaffold/api/__init__.py", line 337, in create_project
    actions, (struct, opts))
  File "/Users/hershel.mehta/miniconda3/envs/advent2017/lib/python3.6/site-packages/pyscaffold/api/__init__.py", line 336, in <lambda>
    struct, opts = reduce(lambda acc, f: invoke_action(f, *acc),
  File "/Users/hershel.mehta/miniconda3/envs/advent2017/lib/python3.6/site-packages/pyscaffold/update.py", line 122, in invoke_action
    struct, opts = action(struct, opts)
  File "/Users/hershel.mehta/miniconda3/envs/advent2017/lib/python3.6/site-packages/pyscaffold/structure.py", line 100, in create_structure
    struct[name], opts, prefix=join_path(prefix, name))
  File "/Users/hershel.mehta/miniconda3/envs/advent2017/lib/python3.6/site-packages/pyscaffold/structure.py", line 95, in create_structure
    utils.create_file(join_path(prefix, name), content, pretend)
  File "/Users/hershel.mehta/miniconda3/envs/advent2017/lib/python3.6/site-packages/pyscaffold/utils.py", line 239, in create_file
    fh.write(content)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1814-1816: ordinal not in range(128)

**Comment by FlorianWilhelm** [comment]
So far I haven't encountered this. Does it only happen if you use `--dsproject`?

@abravalheri, do you have an idea about that? I don't understand why this is ascii anyway.

**Comment by hershelm** [comment]
Yes, only happens with --dsproject

**Comment by FlorianWilhelm** [comment]
@hershelm, could you try to do:
```
pip install -U pyscaffold==3.2.2b1
```
and check with `putup -V` if it really is `3.2.b1`? Then please try with `--dsproject` again and check if the error disappeared. Thanks.

**Comment by hershelm** [comment]
Looks like the --dsproject isn't availabe in `3.2.2b1`

===

(test1) hershel.mehta at mac-C02Y10T3JG5H in ~/test
$ putup -V
PyScaffold 3.2.2b1

(test1) hershel.mehta at mac-C02Y10T3JG5H in ~/test
$ putup --dsproject test_ds
usage: putup [-h] [-p NAME] [-d TEXT] [-l LICENSE] [-u URL] [-f] [-U] [-V]
             [-v] [-vv] [-P | --list-actions]
             [--cookiecutter TEMPLATE | --django] [--gitlab]
             [--namespace NS1[.NS2]] [--no-skeleton] [--pre-commit] [--tox]
             [--travis]
             PROJECT
putup: error: unrecognized arguments: --dsproject

**Comment by FlorianWilhelm** [comment]
@hershelm you have to install the plugin as before with pip.
